### ISSUE TITLE
Publish message to a topic partition

### ISSUE THREAD

**Issue by povilasjur** [obsidiandynamics/kafdrop#166]
As a software developer I need to be able to publish messages to a topic partition using kafdrop.

kafdrop is a great tool. There are cases though when we need an easy way to manually publish messages to topics and be able to manually test our microservices. Being able to public message from kafdrop would let us do that from one tool. Currently we use kafkatool which has this feature. We would be happy to fully replace kafkatool with kafdrop if it had this feature.

**Comment by michalbcz** [comment]
Imho this should be under some feature flag, so you can turn this functionality completely off. Right now according to README.md: "Kafdrop is a web UI for **viewing** Kafka topics and browsing consumer groups" this tool is for readonly operations and this changes semantics of usage because it adds active (write) operations into the mix. Sure it can be useful, but what if you just want tool to view messages for debugging / testing, but don't want let others to send messages created by hand.

**Comment by shreyas-segu** [comment]
This feature might be very helpful to people who want to test stuff locally, I agree with what @michalbcz said, that this needs to be hidden under a feature flag, which will also hide the ability to hide the create topic functionality
If publishing messages manually is out of scope, imo creating topics, partitions manually also belongs to the same category
