### ISSUE TITLE
Support for SASL_SSL

### ISSUE THREAD

**Issue by thammuio** [obsidiandynamics/kafdrop#17]
Does this support SASL_SSL.

**Comment by ekoutanov** [comment]
Discussed in  #9. 

TL;DR: Possibly, but not tested.

**Comment by shaaimin** [comment]
@ekoutanov 
after i added some code on KafkaHighLevelAdminClient.java, it works well for me.
add the following after line28
    if (kafkaConfiguration.getIsSecured()) {
        props.put(CommonClientConfigs.SECURITY_PROTOCOL_CONFIG, kafkaConfiguration.getSecurityProtocol());
        props.put(SaslConfigs.SASL_MECHANISM, kafkaConfiguration.getSaslMechanism());
    }

another issue is exception occurred when show cluster-overview and broker detail page since host in BrokerVO which was got from kafkaMonitor.getBrokers() is null.
also i found a similar case as below.
Yelp/kafka-utils#157

revise the following parts, it works well.
cluster-overview.ftl
line92
                    <td>${b.host?if_exists}</td>
broker-detail.ftl
line42
            <td>${broker.host?if_exists}:${broker.port}</td>

i tried to create a branch and then create pullrequest, it seems no auth for me to do that.

**Comment by ekoutanov** [comment]
Hi @shaaimin. To a PR, it's best to fork the repo, make your change into your master, then raise the PR.

**Comment by shaaimin** [comment]
Hi @ekoutanov. I had raised the PR, please confirm.
