### ISSUE TITLE
Lag value is not accurate.

### ISSUE THREAD

**Issue by anuj-bitbrew** [obsidiandynamics/kafdrop#300]
kafka-consumer-groups.sh --describe --group AnalyticGroup --bootstrap-server kafka-server1:9092
 
the kafka script is giving the lag value as 50k where as whatever value I am getting on the KafDrop UI is less than 10.
Tried refreshing the page but still not getting even close to the actual value.

**Comment by Anirudhra10** [comment]
I am noticing a similar issue as well.

First image shows the lag as seen on command line.
![Screen Shot 2021-09-27 at 10 36 50 AM](https://user-images.githubusercontent.com/8356760/134958360-721dec23-94d5-466b-8fd8-0426da7dfe62.png)

Second image shows the lag from Kafdrop UI.
![Screen Shot 2021-09-27 at 10 36 59 AM](https://user-images.githubusercontent.com/8356760/134958475-4501b018-fdcb-41bf-a507-be3faaed702f.png)

Clearly the lag values are not accurate.

Just looking at the lag value on Kafdrop, it seems the value is the difference between `Last Offset` and `First Offset`, instead of computing the difference between `Last Offset` and `Consumer Offset`
