### ISSUE TITLE
JSON payload's details view is corrupted if has very big numbers where type should be inferred as "long" not "int"

### ISSUE THREAD

**Issue by pranasblk** [obsidiandynamics/kafdrop#338]
**_Actual display:_**
```
{
   "id": 202201180000000000,
...
}
```

**_Expected_**
```
{
"id":202201180000000014,
...
}
```

Interestingly it shows preview id correctly (not parsed payload) before expanding view of payload i.e. stored truncated value in the model after parsing.

**Comment by TomMarquardt1** [comment]
Hello! I am confirming that this is not fixed, since I just ran across this bug.

The UI for Kafdrop is rounding or truncating long numbers when displaying them in the UI.

If I look at the Response payload for the UI request, I see:

`&quot;assetId &quot;: -7210194211959421178`

But in the UI, I see:

"assetId": -7210194211959421000

The correct value in Kafka is -7210194211959421178
