### ISSUE TITLE
Fix Log4j Critical CVE's (CVE-2021-44228, CVE-2021-45046)

### ISSUE THREAD

**Issue by rogue5oul** [obsidiandynamics/kafdrop#347]
Scans of 3.28.0 container shows the following critical vulnerabilities.

# CVE-2021-44228
https://nvd.nist.gov/vuln/detail/CVE-2021-44228
package = /kafdrop-3.28.0/lib/jboss-logging-3.4.2.Final.jar
current version = 2.11.2
fixed version = 2.15
# CVE-2021-45046
https://nvd.nist.gov/vuln/detail/CVE-2021-45046
package = /kafdrop-3.28.0/lib/jboss-logging-3.4.2.Final.jar
current version = 2.11.2
fixed version = 2.16

# Version validation method
```
$ java -jar /kafdrop-3.28.0/lib/jboss-logging-3.4.2.Final.jar -v
```
Validation of version inside container currently gives the following message:
* no main manifest attribute, in /kafdrop-3.28.0/lib/jboss-logging-3.4.2.Final.jar

Would be nice to validate version without having to run scans.

**Comment by programmer04** [comment]
The image which is built from the master branch does not contain the above vulnerabilities, because it uses [jboss-logging-3.4.3.Final.jar](https://github.com/jboss-logging/jboss-logging/releases/tag/3.4.3.Final) which includes [log4j 2 2.16.0](https://github.com/apache/logging-log4j2/blob/rel/2.16.0/RELEASE-NOTES.md#ga-release-2160). Thus to get rid of vulnerabilities please let's release the new version

**Comment by davideicardi** [comment]
Version 3.29.0 just released. Can you please verify which CVE is still relevant?

**Comment by rogue5oul** [comment]
3.29.0 scans are clear of:
* CVE-2021-44228
* CVE-2021-45046
