### ISSUE TITLE
List of consumers is incomplete

### ISSUE THREAD

**Issue by jeffworne** [obsidiandynamics/kafdrop#61]
Hello,

I've noticed that not all consumer groups are listed in Kafdrop. If I look at Kafka Manager for the same topic, I can see all consumers (including temporary unnamed ones).

**Comment by ekoutanov** [comment]
I'm going to hazard a guess and say it's because Kafka Manager is using ZooKeeper. Kafdrop is using the Kafka Admin API, which may be more limited in what it presents. On the flipside, it can work with secured clusters where ZK is not exposed.

**Comment by jeffworne** [comment]
Would using the ZK servers instead of the Kafka ones help?

**Comment by ekoutanov** [comment]
It's still a hypothesis that the issue is due to the Kafka connection. Someone needs to look at the code and verify. Other than some temporary unnamed groups, are you missing any longlived groups?

We made a conscious decision to abandon ZK support as it was dragging us back. Also, ZK is a proverbial 'dead man walking': Kafka themselves are looking to abandon ZK for metadata persistence, and there is even a KIP for that.
