### ISSUE TITLE
Fail to display messages on topics with transaction markers

### ISSUE THREAD

**Issue by jammann** [obsidiandynamics/kafdrop#64]
Hi
I'm testing KafkaDrop for the first time against Kafka 2.2. Everything seems to work and I can easily display messages on topics which have not been written with Kafka transaction.
But on some of our topics, all messages are written transactionally. Normally 2 messages on 2 different topics. So those topics contain the Kafka transaction markers ( as described here https://docs.google.com/document/d/11Jqy_GjUGtdXJK94XGsEIK7CP1SnQGdp2eF0wSw9ra8/edit#heading=h.mylukj7bg1rf)
It seems to me that KafDrop then fails to display ANY messages on these topics, at least the View Message screen remains empty. I can't see any error message in the log, though.
Can you tell me if this is just not currently supported (I might then have a look into it and try to come up with a PR)? Or am I doing something wrong?
Thanks, Joe

**Comment by ekoutanov** [comment]
To be honest there is nothing I can think of that would stop this from happening. Personally, I have not tried Kafdrop with transactions. It is likely a bug. So yes, a PR would be in order :)

**Comment by rognorak** [comment]
@jammann Curious, ran into same issue, did you ever take a look into it?

**Comment by ekoutanov** [comment]
I can reproduce it. The issue is related to the transaction markers, as you correctly deduced, which are interleaved with regular records and can cause issues in some cases — where the consumer is approaching the high-water mark, and still thinks it has records to process, whereas in reality the partition has been exhausted.
Fix will be available shortly.
