### ISSUE TITLE
Differnet host address for the Web UI.

### ISSUE THREAD

**Issue by Alexound** [obsidiandynamics/kafdrop#7]
Hi!

I've installed **Docker** container with **Kafdrop** on my remote Apache Kafka server.
How can I bind Web UI to a different address, other then 'localhost', say, public ip of a server?
The following script is used to start Kafdrop as **Docker** container:

`docker run -d --rm -p 9000:9000 \
    -e ZOOKEEPER_CONNECT=host:port,host:port \
    -e KAFKA_BROKERCONNECT=host:port,host:port \
    -e JVM_OPTS="-Xms32M -Xmx64M" \
    -e SERVER_SERVLET_CONTEXTPATH="/" \
    obsidiandynamics/kafdrop:latest`

Thanks!

**Comment by ekoutanov** [comment]
Hi,

This is a Docker issue rather than a Kafdrop one. By default, docker binds to the loopback interface. You can override this behaviour either in a global config, or by binding to a specific port. Please consult the [docker guide](https://docs.docker.com/v17.09/engine/userguide/networking/default_network/binding/).

Your other options would be to reverse proxy, using something like NGINX with a `proxy_pass` directive. (This is a fairly common solution in the industry.)
