### ISSUE TITLE
Add possibility to remove a topic

### ISSUE THREAD

**Issue by stijnvanbever** [obsidiandynamics/kafdrop#86]
Hello,
It would be great to have the possibility to delete a topic.
While testing streaming applications I need to delete topics multiple times if my schema changes.
Would this fit into Kafdrop? Or is Kafdrop only meant as a read only tool?
Thanks

**Comment by ekoutanov** [comment]
Not it all. While it started as a read-only tool, we had since added some write capabilities too — for example, to create topics. I think the community would appreciate having delete capability, if you're keen on raising a PR?

In the longer term, ideally Kafdrop should do most things that you currently need the CLI for.

**Comment by stijnvanbever** [comment]
I'll see what I can do. PR will follow later

**Comment by ekoutanov** [comment]
Any further thoughts on this @stijnvanbever ?

**Comment by stijnvanbever** [comment]
Been a quite hectic time. I'm picking this up again now.
